import { createContext } from "react";
import { useState } from "react";


export const LocalizationContext = createContext();

function LocalizationProvider(props) {

    const [localization, setLocalization] = useState({
        selectedLanguage: "en",
        en: {
            styleEditor_backgroundColor: "Document Background Color",
            styleEditor_baseColor: "Section Base Color",
            styleEditor_transparentBackground: "Transparent Background",
            styleEditor_randomizeColor: "Randomize Color",
            styleEditor_textFont: "Text Font",
            styleEditor_borderStyle: "Border Style",
            styleEditor_borderWidth: "Border Width",
            styleEditor_verticalMargin: "Vertical Margin",
            styleEditor_horizontalMargin: "Horizontal Margin",
            styleEditor_language: "Language",
            cvEditor_print: "Print this out!",
            sectionSelector_addEducation: "Add Education",
            sectionSelector_addReferences: "Add References",
            sectionSelector_addExperience: "Add Experience",
            sectionSelector_addSkills: "Add Skills Group",
            sectionSelector_addHobbies: "Add Hobbies",
            sectionSelector_addLanguages: "Add Languages",
            sectionSelector_addBio: "Add Bio",
            sectionSelector_addPic: "Add Picture",
            sectionSelector_addContact: "Add Contact",
            sectionSelector_addName: "Add Name",
            sections_education_header: "Education",
            sections_education_courseName: "Education/Course Name",
            sections_education_organisation: "Organisation",
            sections_education_city: "City",
            sections_education_yearRange: "Year of Start - Year of End",
            sections_education_description: "Description",
            sections_references_header: "References",
            sections_references_firstName: "First Name",
            sections_references_lastName: "Last Name",
            sections_references_phone: "Phone",
            sections_references_email: "E-mail",
            sections_experience_header: "Experience",
            sections_experience_company: "Company",
            sections_experience_title: "Title",
            sections_experience_yearRange: "Year of Start - Year of End",
            sections_experience_description: "Description",
            sections_skills_header: "Skills",
            sections_name_header: "Name",
            sections_hobbies_header: "Hobbies",
            sections_languages_header: "Languages",
            sections_bio_header: "About Me",
            sections_contact_header: "Contact",
            sections_contact_phone: "Phone",
            sections_contact_email: "E-mail",
        },
        de: {
            styleEditor_backgroundColor: "Dokument Hintergrund Farbe",
            styleEditor_baseColor: "Basis Teilfarbe",
            styleEditor_transparentBackground: "Transparent Hintergrund",
            styleEditor_randomizeColor: "Farbe Randomisieren",
            styleEditor_textFont: "Text Schriftart",
            styleEditor_borderStyle: "Grenzstil",
            styleEditor_borderWidth: "Grenzbreite",
            styleEditor_verticalMargin: "Senkrecht Rand",
            styleEditor_horizontalMargin: "Waagerecht Rand",
            styleEditor_language: "Sprache",
            cvEditor_print: "Ausdrucken!",
            sectionSelector_addEducation: "Ausbildung Hinzufügen",
            sectionSelector_addReferences: "Referenz Hinzufügen",
            sectionSelector_addExperience: "Erfahrung Hinzufügen",
            sectionSelector_addSkills: "Fähigkeiten Hinzufügen",
            sectionSelector_addHobbies: "Hobbys Hinzufügen",
            sectionSelector_addLanguages: "Sprachen Hinzufügen",
            sectionSelector_addBio: "Bio Hinzufügen",
            sectionSelector_addPic: "Bild Hinzufügen",
            sectionSelector_addContact: "Kontakt Hinzufügen",
            sectionSelector_addName: "Name Hinzufügen",
            sections_education_header: "Ausbildung",
            sections_education_courseName: "Ausbildung/Lehrgang",
            sections_education_organisation: "Organisation",
            sections_education_city: "Stadt",
            sections_education_yearRange: "Anfangsjahr - Endjahr",
            sections_education_description: "Beschreibung",
            sections_references_header: "Referenzen",
            sections_references_firstName: "Vorname",
            sections_references_lastName: "Nachname",
            sections_references_phone: "Telefon",
            sections_references_email: "E-mail",
            sections_experience_header: "Erfahrung",
            sections_experience_company: "Firma",
            sections_experience_title: "Titel",
            sections_experience_yearRange: "Anfangsjahr - Endjahr",
            sections_experience_description: "Beschreibung",
            sections_skills_header: "Fähigkeiten",
            sections_name_header: "Name",
            sections_hobbies_header: "Hobbys",
            sections_languages_header: "Sprachen",
            sections_bio_header: "Über mich",
            sections_contact_header: "Kontakt",
            sections_contact_phone: "Telefon",
            sections_contact_email: "E-mail",
        },
        tr: {
            styleEditor_backgroundColor: "Belge Arka Plan Rengi",
            styleEditor_baseColor: "Bölüm Temel Rengi",
            styleEditor_transparentBackground: "effaf Arka Plan",
            styleEditor_randomizeColor: "Rastgele Renk Seç",
            styleEditor_textFont: "Yazı Tipi",
            styleEditor_borderStyle: "Kenar Stili",
            styleEditor_borderWidth: "Kenar Genişliği",
            styleEditor_verticalMargin: "Dikey Kenar Boşluğu",
            styleEditor_horizontalMargin: "Yatay Kenar Boşluğu",
            styleEditor_language: "Dil",
            cvEditor_print: "Yazdır!",
            sectionSelector_addEducation: "Eğitim Ekle",
            sectionSelector_addReferences: "Referans Ekle",
            sectionSelector_addExperience: "Deneyim Ekle",
            sectionSelector_addSkills: "Beceri Ekle",
            sectionSelector_addHobbies: "Hobi Ekle",
            sectionSelector_addLanguages: "Dil Ekle",
            sectionSelector_addBio: "Hakkımda Ekle",
            sectionSelector_addPic: "Resim Ekle",
            sectionSelector_addContact: "İletişim Ekle",
            sectionSelector_addName: "İsim Ekle",
            sections_education_header: "Eğitim",
            sections_education_courseName: "Bölüm Adı",
            sections_education_organisation: "Eğitim Yeri",
            sections_education_city: "Şehir",
            sections_education_yearRange: "Başlangıç Yılı - Bitiş Yılı",
            sections_education_description: "Açıklama",
            sections_references_header: "Referanslar",
            sections_references_firstName: "İsim",
            sections_references_lastName: "Soyisim",
            sections_references_phone: "Telefon",
            sections_references_email: "E-posta",
            sections_experience_header: "Deneyim",
            sections_experience_company: "Şirket",
            sections_experience_title: "Görev Ünvanı",
            sections_experience_yearRange: "Başlangıç Yılı - Bitiş Yılı",
            sections_experience_description: "Açıklama",
            sections_skills_header: "Beceriler",
            sections_name_header: "İsim",
            sections_hobbies_header: "Hobiler",
            sections_languages_header: "Diller",
            sections_bio_header: "Hakkımda",
            sections_contact_header: "İletişim",
            sections_contact_phone: "Telefon",
            sections_contact_email: "E-posta",
        }
    });

    return (
        <LocalizationContext.Provider value={[localization, setLocalization]}>
            {props.children}
        </LocalizationContext.Provider>
    );
}

export { LocalizationProvider };
